services:
  db:
    build:
      context: .
      dockerfile: Dockerfile.db
    image: my_postgres_image
    restart: always
    environment:
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    volumes:
      - postgres_size_db_data:/var/lib/postgresql/data
      - postgres_size_db_log_data:/logs:z
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U ${POSTGRES_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - custom-network
    container_name: ayaki-coder-home-library-db

  api:
    build:
      context: .
      dockerfile: Dockerfile.size
    image: my_home_library_part2_image
    ports:
      - ${PORT}:${PORT}
    depends_on:
      db:
        condition: service_healthy
    develop:
      watch:
        - action: sync
          path: ./src
          target: /usr/app/src
    restart: always
    environment:
      - PORT=${PORT}
      - DATABASE_URL=${DATABASE_URL}
    env_file:
      - .env
    networks:
      - custom-network
    container_name: ayaki-coder-home-library-api-prod

volumes:
  postgres_size_db_data:
  postgres_size_db_log_data:

networks:
  custom-network:
    driver: bridge
